### PR TITLE
Misc updates

### PR DESCRIPTION
**Pull request by ddsjoberg**
UPDATES:
1. I made the pkgdown site deploy automatically via Travis, and deleted the docs folder.  Everytime you merge a branch into master, the pkgdown site will update automatically.  You can still check the site locally by running `pkgdown::build_site()`.  The site will build in the docs folder, but will not go onto GitHub.  The docs folder is now listed in the `.gitignore` files.  I will need to make sure I actually did this correctly after it's merged with the master branch.
1. Added a min R version of 3.2. cmprsk has a min version of 3.0.  I made the min version of this package 3.2 due to deps.
1. Made some updates to the pkgdown site
1. Added a NEWS.md file
1. I deleted gtsummary as a deps.  To keep examples running for now, I added the gtsummary trial dataset to the package.  This can be removed/modified later.
1. I added the `crr()` S3 method function.  Is that not what you wanted to use?

NOTES:
1. I copied the same pkgdown theme as gtsummary, but there are many many to choose from!
1. What do you think we should do about the method functions from cmprsk?  I see a couple of options:
  - Do you think we should import, then export all the functions?  With roxygen2 we can even import each part of the help file from cmprsk, and the documentation would update as cmprsk updates.
  - Perhaps we could add cmprsk to the Depends field in the DESCRIPTION, then cmprsk would load everytime riskybiz is loaded.  I don't really like this solution.

### CODE REVIEW

**Comment by mljaniczek** [comment]
1. love the gtsummary theme and happy to have it match!
2. I think it makes sense to depend on cmprsk since all we are is a wrapper. Can you elaborate on why you would prefer to import/export all the cmprsk functions? I'm open to it!

**Comment by ddsjoberg** [comment]
Good point about being a wrapper. If we do add cmprsk to `Depends:`, when a user loads riskybiz and searchs for the help file of `?crr`---rather than getting the help file for `riskybiz::crr()`, they're presented with the option to choose which file to view.  If they choose cmprisk (which may seem like good instincts to a user who has previously used cmprsk), they won't see the amazing formula notation.
image

Anyway, absolutely something to think through more!

**Comment by ddsjoberg** [comment]
Hmmmm, the checks are not passing on the earliest versions of R.  I wonder if there is something in the code that is not compatible early R versions?
https://travis-ci.org/margarethannum/riskybiz/builds/609829923?utm_medium=notification&utm_source=github_status

**Comment by mljaniczek** [comment]
@ddsjoberg CMD check error appears to be coming from running the example : 

`>  # using new wrapper function, accepts data and formula
>  mod_new <- crr(Surv(ttdeath, grey) ~ age + trt + grade, trial2)
Error in .subset2(x, i) : invalid subscript type 'symbol'
Calls: crr -> crr.formula -> [[ -> [[.tbl_df`

I'm not sure why your minor changes to the function code would have caused this though?

**Pull request merged**
